// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSoft.Company.ORD.Order.Data.Db.Contexts;

#nullable disable

namespace VSoft.Company.ORD.Order.Data.Migrate.Real.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20230425132524_InitOrder")]
    partial class InitOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VSoft.Company.ORD.Order.Data.Entity.Models.MOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NULL");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint(20)");

                    b.Property<long?>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime?>("EditedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("EditedUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("NULL");

                    b.Property<bool?>("IsDraft")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("1");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "FK_Customer_TO_Order");

                    b.HasIndex(new[] { "UserId" }, "FK_User_TO_Order");

                    b.HasIndex(new[] { "EditedUserId" }, "FK_User_TO_Order1");

                    b.ToTable("Order", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
